#drop table flaimme.ADM_OPTIMAL_MOVES;

create table flaimme.ADM_OPTIMAL_MOVES (
TRACK_LEFT VARCHAR(160),
DECK_LEFT VARCHAR(20),
TURNS_TO_FINISH int,
DRAW_ODDS VARCHAR(35),
PRIMARY KEY (TRACK_LEFT(160), DRAW_ODDS(35), DECK_LEFT(20)));

