
SET SQL_SAFE_UPDATES = 0;
DELETE FROM BREAKAWAY_BET where 1 = 1;
DELETE FROM TOURNAMENT_RESULT where 1 = 1;
DELETE FROM DECK_STATUS where 1 = 1;
DELETE FROM BREAKAWAY_BET_CARDS where 1 = 1;
#DELETE FROM TOURNAMENT where 1 = 1;